### ISSUE TITLE
webui select model list is empty

### ISSUE THREAD

**Issue by Dev-Wiki** [Dhruvgera/LocalAI-frontend#5]
docker compose install localai and web ui:

```yaml
version: '3.6'

services:
  api:
    image: quay.io/go-skynet/local-ai:latest
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./models:/models:cached
    command: ["/usr/bin/local-ai" ]

  frontend:
    image: quay.io/go-skynet/localai-frontend:master
    ports:
      - 3000:3000
```

build result:
```bash
$ docker-compose up -d --pull always
[+] Running 2/2
 ✔ frontend Pulled                                                                                                 3.2s
 ✔ api Pulled                                                                                                      3.2s
[+] Building 0.0s (0/0)
[+] Running 2/0
 ✔ Container localai-frontend-1  Running                                                                           0.0s
 ✔ Container localai-api-1       Running                                                                           0.0s


$ curl http://localhost:8080/v1/models
{"object":"list","data":[{"id":"ggml-gpt4all-j","object":"model"}]}

```

but,the webui:
![image](https://github.com/Dhruvgera/LocalAI-frontend/assets/12946956/8093d210-7522-462b-8a6c-4ba3eca83fab)
